server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://pro-club-oss
          predicates:
            - Path=/oss/**
        - id: auth
          uri: lb://pro-club-auth
          predicates:
            - Path=/auth/**
        - id: subject
          uri: lb://pro-club-subject
          predicates:
            - Path=/subject/**